"""added size to order item

Revision ID: b23ef7fef0cf
Revises: 26a1bfcd41d0
Create Date: 2024-12-06 01:03:06.137871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23ef7fef0cf'
down_revision: Union[str, None] = '26a1bfcd41d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='productsizeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'size')
    # ### end Alembic commands ###
