"""update user table

Revision ID: fecfa829059e
Revises: 571a75a13490
Create Date: 2024-12-02 23:03:54.416579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecfa829059e'
down_revision: Union[str, None] = '571a75a13490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userroles AS ENUM ('ADMIN', 'USER')")

    # Alter the column to use the enum type
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'USER', name='userroles'),
               existing_nullable=False,
               postgresql_using="role::userroles")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userroles'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
